import { PeriodElement } from "../types/periodElement";

export const periodicTable: PeriodElement[] = [
	{ name: "Hydrogen", symbol: "H", period: 1, group: 1, atomicNumber: 1 },
	{ name: "Helium", symbol: "He", period: 1, group: 18, atomicNumber: 2 },
	{ name: "Lithium", symbol: "Li", period: 2, group: 1, atomicNumber: 3 },
	{ name: "Beryllium", symbol: "Be", period: 2, group: 2, atomicNumber: 4 },
	{ name: "Boron", symbol: "B", period: 2, group: 13, atomicNumber: 5 },
	{ name: "Carbon", symbol: "C", period: 2, group: 14, atomicNumber: 6 },
	{ name: "Nitrogen", symbol: "N", period: 2, group: 15, atomicNumber: 7 },
	{ name: "Oxygen", symbol: "O", period: 2, group: 16, atomicNumber: 8 },
	{ name: "Fluorine", symbol: "F", period: 2, group: 17, atomicNumber: 9 },
	{ name: "Neon", symbol: "Ne", period: 2, group: 18, atomicNumber: 10 },

	// Period 3
	{ name: "Sodium", symbol: "Na", period: 3, group: 1, atomicNumber: 11 },
	{ name: "Magnesium", symbol: "Mg", period: 3, group: 2, atomicNumber: 12 },
	{ name: "Aluminum", symbol: "Al", period: 3, group: 13, atomicNumber: 13 },
	{ name: "Silicon", symbol: "Si", period: 3, group: 14, atomicNumber: 14 },
	{ name: "Phosphorus", symbol: "P", period: 3, group: 15, atomicNumber: 15 },
	{ name: "Sulfur", symbol: "S", period: 3, group: 16, atomicNumber: 16 },
	{ name: "Chlorine", symbol: "Cl", period: 3, group: 17, atomicNumber: 17 },
	{ name: "Argon", symbol: "Ar", period: 3, group: 18, atomicNumber: 18 },

	// Period 4
	{ name: "Potassium", symbol: "K", period: 4, group: 1, atomicNumber: 19 },
	{ name: "Calcium", symbol: "Ca", period: 4, group: 2, atomicNumber: 20 },
	{ name: "Scandium", symbol: "Sc", period: 4, group: 3, atomicNumber: 21 },
	{ name: "Titanium", symbol: "Ti", period: 4, group: 4, atomicNumber: 22 },
	{ name: "Vanadium", symbol: "V", period: 4, group: 5, atomicNumber: 23 },
	{ name: "Chromium", symbol: "Cr", period: 4, group: 6, atomicNumber: 24 },
	{ name: "Manganese", symbol: "Mn", period: 4, group: 7, atomicNumber: 25 },
	{ name: "Iron", symbol: "Fe", period: 4, group: 8, atomicNumber: 26 },
	{ name: "Cobalt", symbol: "Co", period: 4, group: 9, atomicNumber: 27 },
	{ name: "Nickel", symbol: "Ni", period: 4, group: 10, atomicNumber: 28 },
	{ name: "Copper", symbol: "Cu", period: 4, group: 11, atomicNumber: 29 },
	{ name: "Zinc", symbol: "Zn", period: 4, group: 12, atomicNumber: 30 },
	{ name: "Gallium", symbol: "Ga", period: 4, group: 13, atomicNumber: 31 },
	{ name: "Germanium", symbol: "Ge", period: 4, group: 14, atomicNumber: 32 },
	{ name: "Arsenic", symbol: "As", period: 4, group: 15, atomicNumber: 33 },
	{ name: "Selenium", symbol: "Se", period: 4, group: 16, atomicNumber: 34 },
	{ name: "Bromine", symbol: "Br", period: 4, group: 17, atomicNumber: 35 },
	{ name: "Krypton", symbol: "Kr", period: 4, group: 18, atomicNumber: 36 },

	// Period 5
	{ name: "Rubidium", symbol: "Rb", period: 5, group: 1, atomicNumber: 37 },
	{ name: "Strontium", symbol: "Sr", period: 5, group: 2, atomicNumber: 38 },
	{ name: "Yttrium", symbol: "Y", period: 5, group: 3, atomicNumber: 39 },
	{ name: "Zirconium", symbol: "Zr", period: 5, group: 4, atomicNumber: 40 },
	{ name: "Niobium", symbol: "Nb", period: 5, group: 5, atomicNumber: 41 },
	{ name: "Molybdenum", symbol: "Mo", period: 5, group: 6, atomicNumber: 42 },
	{ name: "Technetium", symbol: "Tc", period: 5, group: 7, atomicNumber: 43 },
	{ name: "Ruthenium", symbol: "Ru", period: 5, group: 8, atomicNumber: 44 },
	{ name: "Rhodium", symbol: "Rh", period: 5, group: 9, atomicNumber: 45 },
	{ name: "Palladium", symbol: "Pd", period: 5, group: 10, atomicNumber: 46 },
	{ name: "Silver", symbol: "Ag", period: 5, group: 11, atomicNumber: 47 },
	{ name: "Cadmium", symbol: "Cd", period: 5, group: 12, atomicNumber: 48 },
	{ name: "Indium", symbol: "In", period: 5, group: 13, atomicNumber: 49 },
	{ name: "Tin", symbol: "Sn", period: 5, group: 14, atomicNumber: 50 },
	{ name: "Antimony", symbol: "Sb", period: 5, group: 15, atomicNumber: 51 },
	{ name: "Tellurium", symbol: "Te", period: 5, group: 16, atomicNumber: 52 },
	{ name: "Iodine", symbol: "I", period: 5, group: 17, atomicNumber: 53 },
	{ name: "Xenon", symbol: "Xe", period: 5, group: 18, atomicNumber: 54 },

	// Period 6 (lanthanoids inline or below)
	{ name: "Cesium", symbol: "Cs", period: 6, group: 1, atomicNumber: 55 },
	{ name: "Barium", symbol: "Ba", period: 6, group: 2, atomicNumber: 56 },
	// lanthanides 57–71 (often placed in f‑block)
	{ name: "Lanthanum", symbol: "La", period: 6, group: 3, atomicNumber: 57 },
	{ name: "Cerium", symbol: "Ce", period: 6, group: 3, atomicNumber: 58 },
	{ name: "Praseodymium", symbol: "Pr", period: 6, group: 3, atomicNumber: 59 },
	{ name: "Neodymium", symbol: "Nd", period: 6, group: 3, atomicNumber: 60 },
	{ name: "Promethium", symbol: "Pm", period: 6, group: 3, atomicNumber: 61 },
	{ name: "Samarium", symbol: "Sm", period: 6, group: 3, atomicNumber: 62 },
	{ name: "Europium", symbol: "Eu", period: 6, group: 3, atomicNumber: 63 },
	{ name: "Gadolinium", symbol: "Gd", period: 6, group: 3, atomicNumber: 64 },
	{ name: "Terbium", symbol: "Tb", period: 6, group: 3, atomicNumber: 65 },
	{ name: "Dysprosium", symbol: "Dy", period: 6, group: 3, atomicNumber: 66 },
	{ name: "Holmium", symbol: "Ho", period: 6, group: 3, atomicNumber: 67 },
	{ name: "Erbium", symbol: "Er", period: 6, group: 3, atomicNumber: 68 },
	{ name: "Thulium", symbol: "Tm", period: 6, group: 3, atomicNumber: 69 },
	{ name: "Ytterbium", symbol: "Yb", period: 6, group: 3, atomicNumber: 70 },
	{ name: "Lutetium", symbol: "Lu", period: 6, group: 3, atomicNumber: 71 },
	{ name: "Hafnium", symbol: "Hf", period: 6, group: 4, atomicNumber: 72 },
	{ name: "Tantalum", symbol: "Ta", period: 6, group: 5, atomicNumber: 73 },
	{ name: "Tungsten", symbol: "W", period: 6, group: 6, atomicNumber: 74 },
	{ name: "Rhenium", symbol: "Re", period: 6, group: 7, atomicNumber: 75 },
	{ name: "Osmium", symbol: "Os", period: 6, group: 8, atomicNumber: 76 },
	{ name: "Iridium", symbol: "Ir", period: 6, group: 9, atomicNumber: 77 },
	{ name: "Platinum", symbol: "Pt", period: 6, group: 10, atomicNumber: 78 },
	{ name: "Gold", symbol: "Au", period: 6, group: 11, atomicNumber: 79 },
	{ name: "Mercury", symbol: "Hg", period: 6, group: 12, atomicNumber: 80 },
	{ name: "Thallium", symbol: "Tl", period: 6, group: 13, atomicNumber: 81 },
	{ name: "Lead", symbol: "Pb", period: 6, group: 14, atomicNumber: 82 },
	{ name: "Bismuth", symbol: "Bi", period: 6, group: 15, atomicNumber: 83 },
	{ name: "Polonium", symbol: "Po", period: 6, group: 16, atomicNumber: 84 },
	{ name: "Astatine", symbol: "At", period: 6, group: 17, atomicNumber: 85 },
	{ name: "Radon", symbol: "Rn", period: 6, group: 18, atomicNumber: 86 },

	// Period 7 (actinides inline or below)
	{ name: "Francium", symbol: "Fr", period: 7, group: 1, atomicNumber: 87 },
	{ name: "Radium", symbol: "Ra", period: 7, group: 2, atomicNumber: 88 },
	{ name: "Actinium", symbol: "Ac", period: 7, group: 3, atomicNumber: 89 },
	{ name: "Thorium", symbol: "Th", period: 7, group: 3, atomicNumber: 90 },
	{ name: "Protactinium", symbol: "Pa", period: 7, group: 3, atomicNumber: 91 },
	{ name: "Uranium", symbol: "U", period: 7, group: 3, atomicNumber: 92 },
	{ name: "Neptunium", symbol: "Np", period: 7, group: 3, atomicNumber: 93 },
	{ name: "Plutonium", symbol: "Pu", period: 7, group: 3, atomicNumber: 94 },
	{ name: "Americium", symbol: "Am", period: 7, group: 3, atomicNumber: 95 },
	{ name: "Curium", symbol: "Cm", period: 7, group: 3, atomicNumber: 96 },
	{ name: "Berkelium", symbol: "Bk", period: 7, group: 3, atomicNumber: 97 },
	{ name: "Californium", symbol: "Cf", period: 7, group: 3, atomicNumber: 98 },
	{ name: "Einsteinium", symbol: "Es", period: 7, group: 3, atomicNumber: 99 },
	{ name: "Fermium", symbol: "Fm", period: 7, group: 3, atomicNumber: 100 },
	{ name: "Mendelevium", symbol: "Md", period: 7, group: 3, atomicNumber: 101 },
	{ name: "Nobelium", symbol: "No", period: 7, group: 3, atomicNumber: 102 },
	{ name: "Lawrencium", symbol: "Lr", period: 7, group: 3, atomicNumber: 103 },
	{ name: "Rutherfordium", symbol: "Rf", period: 7, group: 4, atomicNumber: 104 },
	{ name: "Dubnium", symbol: "Db", period: 7, group: 5, atomicNumber: 105 },
	{ name: "Seaborgium", symbol: "Sg", period: 7, group: 6, atomicNumber: 106 },
	{ name: "Bohrium", symbol: "Bh", period: 7, group: 7, atomicNumber: 107 },
	{ name: "Hassium", symbol: "Hs", period: 7, group: 8, atomicNumber: 108 },
	{ name: "Meitnerium", symbol: "Mt", period: 7, group: 9, atomicNumber: 109 },
	{ name: "Darmstadtium", symbol: "Ds", period: 7, group: 10, atomicNumber: 110 },
	{ name: "Roentgenium", symbol: "Rg", period: 7, group: 11, atomicNumber: 111 },
	{ name: "Copernicium", symbol: "Cn", period: 7, group: 12, atomicNumber: 112 },
	{ name: "Nihonium", symbol: "Nh", period: 7, group: 13, atomicNumber: 113 },
	{ name: "Flerovium", symbol: "Fl", period: 7, group: 14, atomicNumber: 114 },
	{ name: "Moscovium", symbol: "Mc", period: 7, group: 15, atomicNumber: 115 },
	{ name: "Livermorium", symbol: "Lv", period: 7, group: 16, atomicNumber: 116 },
	{ name: "Tennessine", symbol: "Ts", period: 7, group: 17, atomicNumber: 117 },
	{ name: "Oganesson", symbol: "Og", period: 7, group: 18, atomicNumber: 118 }
];

export default periodicTable;